#! /usr/bin/env sh
tmux has-session -t MST

if [[ $? != 0 ]]
then
  cd ~/Projects/sandbox
  tmux detach
  tmux new-session -s MST -n editor -d
  tmux send-keys -t MST 'vim' C-m
  tmux new-window -n servers -t MST
  tmux split-window -v -t MST:2
  tmux send-keys -t MST:2.2 'git status' C-m
  tmux send-keys -t MST:2.1 'node' C-m
  tmux new-window -n Scratch -t MST
  tmux send-keys -t MST:3 'brewup' C-m
  tmux select-window -t MST:1
fi
tmux attach -t MST
