#! /usr/bin/env sh
tmux has-session -t MTC

if [[ $? != 0 ]]
then
  cd ~/Projects/mtc-teaching-center
  tmux detach
  tmux new-session -s MTC -n editor -d
  tmux send-keys -t MTC 'vim' C-m
  tmux split-window -h -t MTC -p 30
  tmux new-window -n servers -t MTC
  tmux split-window -v -t MTC:2 -p 35
  tmux split-window -h -t MTC:2.1 -p 30
  tmux send-keys -t MTC:2.1 'ranger' C-m
  tmux send-keys -t MTC:2.3 'git status' C-m
  tmux send-keys -t MTC:2.2 'cd WAM' C-m
  tmux send-keys -t MTC:2.2 'sudo ./wamNew.bat'
  tmux new-window -n Scratch -t MTC
  tmux send-keys -t MTC:3 'brewup' C-m
  tmux select-window -t MTC:1
fi
tmux attach -t MTC
